export const CRYPTO_IDS_CREATE = 'CRYPTO_IDS_CREATE';
export const CRYPTO_IDS_LOGIN = 'CRYPTO_IDS_LOGIN';
export const CRYPTO_IDS_SET = 'CRYPTO_IDS_SET';
export const CRYPTO_IDS_CLEAR = 'CRYPTO_IDS_CLEAR';

export const CRYPTO_IDS_LIST_APPEND = 'CRYPTO_IDS_LIST_APPEND';
export const CRYPTO_IDS_LIST_SET = 'CRYPTO_IDS_LIST_SET';
export const CRYPTO_IDS_LIST_CLEAR = 'CRYPTO_IDS_LIST_CLEAR';

export const CRYPTO_IDS_ERROR_SET = 'CRYPTO_IDS_ERROR_SET';
export const CRYPTO_IDS_ERROR_CLEAR = 'CRYPTO_IDS_ERROR_CLEAR';
