export const CRYPTO_LIST_SET = 'CRYPTO_LIST_SET';
export const CRYPTO_LIST_COMPOSE = 'CRYPTO_LIST_COMPOSE';
export const CRYPTO_LIST_CLEAR = 'CRYPTO_LIST_CLEAR';

export const CRYPTO_LIST_PORTFOLIO_COMPOSE = 'CRYPTO_LIST_PORTFOLIO_COMPOSE';
export const CRYPTO_LIST_PORTFOLIO_APPEND = 'CRYPTO_LIST_PORTFOLIO_APPEND';
export const CRYPTO_LIST_PORTFOLIO_CLEAR = 'CRYPTO_LIST_PORTFOLIO_CLEAR';

export const CRYPTO_GLOBAL_SET = 'CRYPTO_GLOBAL_SET';
export const CRYPTO_GLOBAL_APPEND_TOTAL_CRYPTO = 'CRYPTO_GLOBAL_APPEND_TOTAL_CRYPTO';
