export const PORTFOLIO_SET = 'PORTFOLIO_SET';
export const PORTFOLIO_CLEAR = 'PORTFOLIO_CLEAR';

export const PORTFOLIO_ERROR_SET = 'PORTFOLIO_ERROR_SET';
export const PORTFOLIO_ERROR_CLEAR = 'PORTFOLIO_ERROR_CLEAR';

export const PORTFOLIO_SUCCESS_SET = 'PORTFOLIO_SUCCESS_SET';
export const PORTFOLIO_SUCCESS_CLEAR = 'PORTFOLIO_SUCCESS_CLEAR';

export const PORTFOLIOS_LIST_APPEND = 'PORTFOLIOS_LIST_APPEND';
export const PORTFOLIOS_LIST_SET = 'PORTFOLIOS_LIST_SET';
export const PORTFOLIOS_LIST_CLEAR = 'PORTFOLIOS_LIST_CLEAR';
